apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-depl
  labels:
    app: front_end
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: front_end
  template:
    metadata:
      labels:
        app: front_end
    spec: 
      containers:
      - name: front-end-img
        image: 01628229754/frontend:d4c9550639208ca874e5c109642782ecd642d090
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app: front_end
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 31041
