apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-service-depl
  labels:
    app: journal_service
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: journal_service
  template:
    metadata:
      labels:
        app: journal_service
    spec: 
      containers:
      - name: journal-service-img
        image: 01628229754/journal-service:dc007cb5ec7d4c74d9e63c6cdbdc5708cda16337
        ports:
        - containerPort: 8088
        env:
          - name: DATASOURCE_URL
            value: "jdbc:mysql://mysql-service:3306/journal?createDatabaseIfNotExist=true"
          - name: KEYCLOAK_URL
            value: "10.10.171.33:8080"
          - name: KEYCLOAK_ISSUER_URL
            value: "http://130.237.83.249:2506/realms/lab1"
          - name: KEYCLOAK_CLIENT_SECRET
            value: "r6tIeTGZJTVxttSxQxyL9EnOguUkcOnx"
---
apiVersion: v1
kind: Service
metadata:
  name: journal-service-service
spec:
  selector:
    app: journal_service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8088
      nodePort: 31031
