apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-depl
  labels:
    app: message_service
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: message_service
  template:
    metadata:
      labels:
        app: message_service
    spec: 
      containers:
      - name: message-service-img
        image: 01628229754/message-service:206a5b410822e53dfc9fdd90ada711856e321ddf
        ports:
        - containerPort: 8089
        env:
          - name: DATASOURCE_URL
            value: "jdbc:mysql://mysql-service:3306/journal?createDatabaseIfNotExist=true"
          - name: KEYCLOAK_URL
            value: "10.10.171.33:8080"
          - name: KEYCLOAK_ISSUER_URL
            value: "http://130.237.83.249:2506/realms/lab1"
          - name: KEYCLOAK_CLIENT_SECRET
            value: "r6tIeTGZJTVxttSxQxyL9EnOguUkcOnx"
---
apiVersion: v1
kind: Service
metadata:
  name: message-service-service
spec:
  selector:
    app: message_service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8089
      nodePort: 31033
