apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-depl
  labels:
    app: mongo_db
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mongo_db
  template:
    metadata:
      labels:
        app: mongo_db
    spec: 
      containers:
      - name: mongo-db-con
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
spec:
  selector:
    app: mongo_db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

