apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root-ingress
  namespace: default
spec:
  rules:
  - host: lab2.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: front-end-service
            port: 
              number: 5173
