apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-depl
  labels:
    app: search_service
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: search_service
  template:
    metadata:
      labels:
        app: search_service
    spec: 
      containers:
      - name: search-service-img
        image: 01628229754/search-service:365430147cea9ed30003b95ffe7ca29dcf1154c4
        ports:
        - containerPort: 8080
        env:
          - name: DATASOURCE_URL
            value: "jdbc:mysql://mysql-service:3306/journal?createDatabaseIfNotExist=true"
          - name: KEYCLOAK_URL
            value: "10.10.171.33:8080"
          - name: KEYCLOAK_ISSUER_URL
            value: "http://130.237.83.249:2506/realms/lab1"
          - name: KEYCLOAK_CLIENT_SECRET
            value: "r6tIeTGZJTVxttSxQxyL9EnOguUkcOnx"
---
apiVersion: v1
kind: Service
metadata:
  name: search-service-service
spec:
  selector:
    app: search_service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8080
      nodePort: 31034
